/**
 * Cities with Wikipedia article references
 * Used for interactive city info panels and history display
 */
export const CITIES_WITH_WIKI = {
  islamabad: {
    name: 'Islamabad',
    wikiSlug: 'Islamabad',
    population: '1,014,825',
    founded: '1960',
    province: 'Islamabad Capital Territory',
    highlights: ['Capital of Pakistan', 'Planned city', 'Faisal Mosque', 'Margalla Hills'],
  },
  karachi: {
    name: 'Karachi',
    wikiSlug: 'Karachi',
    population: '14,910,352',
    founded: '1729',
    province: 'Sindh',
    highlights: ['Financial capital', 'Largest city', 'Port city', 'Quaid-e-Azam Mausoleum'],
  },
  lahore: {
    name: 'Lahore',
    wikiSlug: 'Lahore',
    population: '11,126,285',
    founded: '985',
    province: 'Punjab',
    highlights: ['Cultural capital', 'Badshahi Mosque', 'Lahore Fort', 'Mughal heritage'],
  },
  rawalpindi: {
    name: 'Rawalpindi',
    wikiSlug: 'Rawalpindi',
    population: '2,098,231',
    founded: '1493',
    province: 'Punjab',
    highlights: ['Military HQ (GHQ)', 'Twin cities with Islamabad', 'Colonial-era architecture'],
  },
  peshawar: {
    name: 'Peshawar',
    wikiSlug: 'Peshawar',
    population: '1,970,042',
    founded: '539 BCE',
    province: 'Khyber Pakhtunkhwa',
    highlights: ['Oldest living city in South Asia', 'Qissa Khwani Bazaar', 'Khyber Pass gateway'],
  },
  quetta: {
    name: 'Quetta',
    wikiSlug: 'Quetta',
    population: '1,001,205',
    founded: '1876',
    province: 'Balochistan',
    highlights: ['Fruit gardens', 'Hazarganji Chiltan National Park', 'Provincial capital'],
  },
  multan: {
    name: 'Multan',
    wikiSlug: 'Multan',
    population: '1,872,000',
    founded: 'Ancient (pre-500 BCE)',
    province: 'Punjab',
    highlights: ['City of Saints', 'Blue pottery', 'Ancient Sufi shrines'],
  },
  faisalabad: {
    name: 'Faisalabad',
    wikiSlug: 'Faisalabad',
    population: '3,204,726',
    founded: '1895',
    province: 'Punjab',
    highlights: ['Manchester of Pakistan', 'Textile industry hub'],
  },
  sialkot: {
    name: 'Sialkot',
    wikiSlug: 'Sialkot',
    population: '656,700',
    founded: 'Ancient',
    province: 'Punjab',
    highlights: ['Sports goods capital', 'Surgical instruments', 'Poet Iqbal birthplace'],
  },
  muzaffarabad: {
    name: 'Muzaffarabad',
    wikiSlug: 'Muzaffarabad',
    population: '122,290',
    founded: '1652',
    province: 'Azad Kashmir',
    highlights: ['Capital of Azad Kashmir', 'Neelum & Jhelum confluence', 'Red Fort'],
  },
  hyderabad: {
    name: 'Hyderabad',
    wikiSlug: 'Hyderabad,_Sindh',
    population: '1,732,693',
    founded: '1768',
    province: 'Sindh',
    highlights: ['Bangle making', 'Hyderabad Fort', 'Second largest city in Sindh'],
  },
};